# Generated by Django 5.2.4 on 2025-07-05 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='interest_categories',
            field=models.ManyToManyField(null=True, to='challenges.category'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
