# Generated by Django 5.2.4 on 2025-07-05 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_interest_categories_user_profile_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
