# Generated by Django 5.2.4 on 2025-07-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_user_email'),
        ('challenges', '0002_remove_category_challenge_remove_category_color_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interest_categories',
            field=models.ManyToManyField(to='challenges.category'),
        ),
    ]
