# Generated by Django 5.2.4 on 2025-07-06 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="interest_categories",
        ),
        migrations.AddField(
            model_name="user",
            name="interest_categories",
            field=models.CharField(
                choices=[
                    ("학습 / 공부", "학습 / 공부"),
                    ("커리어 / 직무", "커리어 / 직무"),
                    ("운동 / 건강", "운동 / 건강"),
                    ("마음 / 루틴", "마음 / 루틴"),
                    ("정리 / 관리", "정리 / 관리"),
                    ("취미", "취미"),
                    ("기타", "기타"),
                ],
                default="학습 / 공부",
                max_length=20,
            ),
        ),
    ]
