# Generated by Django 5.2.4 on 2025-07-07 15:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0015_merge_0013_delete_badge_0014_goalrecord_goal_progress'),
        ('home', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='badge',
            unique_together={('user', 'challenge')},
        ),
    ]
