# Generated by Django 5.2.4 on 2025-07-06 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0009_goal_date_goal_image"),
        ("community", "0003_remove_comment_challenge_remove_post_challenge_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="challenge",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="challenges.challenge",
            ),
        ),
    ]
