# Generated by Django 5.2.4 on 2025-07-07 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0011_goalrecord"),
        ("community", "0004_post_challenge"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="goal_progress",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="challenges.goalprogress",
            ),
        ),
    ]
