# Generated by Django 5.2.4 on 2025-07-08 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="is_deleted",
            field=models.BooleanField(default=False),
        ),
    ]
