# Generated by Django 5.2.4 on 2025-07-05 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='challenge',
        ),
        migrations.RemoveField(
            model_name='category',
            name='color_code',
        ),
        migrations.AddField(
            model_name='challenge',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='challenges.category'),
        ),
    ]
