# Generated by Django 5.2.4 on 2025-07-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_remove_challenge_goal_goal_goalprogress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='frequency',
            field=models.CharField(choices=[('daily', '매일'), ('weekday', '평일'), ('weekend', '주말'), ('every_other_day', '격일'), ('weekly', '주 1회'), ('twice_a_week', '주 2회'), ('montly', '월 1회')], default='daily', max_length=20),
        ),
    ]
