# Generated by Django 5.2.4 on 2025-07-06 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0003_alter_category_name_alter_challenge_category"),
        ("challenges", "0005_badge_awarded_at_badge_category"),
    ]

    operations = []
