# Generated by Django 5.2.4 on 2025-07-06 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0006_merge_20250706_1553"),
    ]

    operations = [
        migrations.AlterField(
            model_name="challenge",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="challenges.category",
            ),
        ),
    ]
