# Generated by Django 5.2.4 on 2025-07-06 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0007_alter_challenge_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="challenge",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="challenge_images/"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(
                choices=[
                    ("학습 / 공부", "학습 / 공부"),
                    ("커리어 / 직무", "커리어 / 직무"),
                    ("운동 / 건강", "운동 / 건강"),
                    ("마음 / 루틴", "마음 / 루틴"),
                    ("정리 / 관리", "정리 / 관리"),
                    ("취미", "취미"),
                    ("기타", "기타"),
                ],
                default="학습 / 공부",
                max_length=50,
                unique=True,
            ),
        ),
    ]
