# Generated by Django 5.2.4 on 2025-07-06 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0008_challenge_image_alter_category_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goal",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="goals_image/"),
        ),
    ]
