# Generated by Django 5.2.4 on 2025-07-07 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0009_goal_date_goal_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='goal',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
