# Generated by Django 5.2.4 on 2025-07-07 08:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0011_goalrecord"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalprogress",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="goalprogress",
            name="date",
            field=models.DateField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="goalprogress",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="goal_progress/"),
        ),
        migrations.AlterField(
            model_name="goalrecord",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
