# Generated by Django 5.2.4 on 2025-07-07 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0011_goalrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
