# Generated by Django 5.2.4 on 2025-07-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0012_challenge_is_completed'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Badge',
        ),
    ]
