# Generated by Django 5.2.4 on 2025-07-07 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0012_goalprogress_content_goalprogress_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalprogress",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="goal_progress_images/"
            ),
        ),
    ]
