# Generated by Django 5.2.4 on 2025-07-07 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0013_alter_goalprogress_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="goalrecord",
            name="goal_progress",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="record",
                to="challenges.goalprogress",
            ),
        ),
    ]
