# Generated by Django 5.1.7 on 2025-07-07 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0013_delete_badge'),
        ('challenges', '0014_goalrecord_goal_progress'),
    ]

    operations = [
    ]
