# Generated by Django 5.2.4 on 2025-07-07 13:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("challenges", "0015_merge_0013_delete_badge_0014_goalrecord_goal_progress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goalprogress",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
